language: scala

scala:
  - 2.12.1

script:
  - sbt clean compile test tut coverage coverageReport

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash) -r $TRAVIS_REPO_SLUG
