language: scala

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

scala:
  - 2.12.1

script:
  - ./.travis.sh 

jdk:
  - oraclejdk8

after_success:
  - codecov
